### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by gutengzczy** [lizhuangzi/IGAN#1]
Thanks for your excellent work on IGAN! May I ask how did you do the visualization work in your paper, especially Figure 8 and Figure 4? They are cool！Thanks a lot!

**Comment by lizhuangzi** [comment]
Thanks, 
Figure 4 is only a sketch map that drawn by Visio. 
For Figure 8, we firstly collect output SR images of these methods, and then use Python to crop the same region in the images and thus we get corresponding local output results (is also .png file). Finally, we use Latex to compose these local results in order.

**Comment by gutengzczy** [comment]
Got it, thanks a lot!
